name: Test
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  build:
    runs-on: '${{ matrix.os }}'
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            python-version: '3.10'
            FLASK: 3.1.2
          - os: ubuntu-latest
            python-version: '3.10'
            FLASK: 3.0.3
          - os: ubuntu-latest
            python-version: '3.10'
            FLASK: 2.3.3
          - os: ubuntu-latest
            python-version: '3.11'
            FLASK: 3.1.2
          - os: ubuntu-latest
            python-version: '3.11'
            FLASK: 3.0.3
          - os: ubuntu-latest
            python-version: '3.11'
            FLASK: 2.3.3
          - os: ubuntu-latest
            python-version: '3.12'
            FLASK: 3.1.2
          - os: ubuntu-latest
            python-version: '3.12'
            FLASK: 3.0.3
          - os: ubuntu-latest
            python-version: '3.12'
            FLASK: 2.3.3
          - os: ubuntu-latest
            python-version: '3.13'
            FLASK: 3.1.2
          - os: ubuntu-latest
            python-version: '3.13'
            FLASK: 3.0.3
          - os: ubuntu-latest
            python-version: '3.13'
            FLASK: 2.3.3
          - os: ubuntu-latest
            python-version: '3.14'
            FLASK: 3.1.2
          - os: ubuntu-latest
            python-version: '3.14'
            FLASK: 3.0.3
          - os: ubuntu-latest
            python-version: '3.14'
            FLASK: 2.3.3
    steps:
      - name: Install apt dependencies
        run: |
          set -ex
          sudo apt update
          sudo apt install -y ldap-utils slapd enchant-2 libldap2-dev libsasl2-dev apparmor-utils
      - name: Disable AppArmor
        run: |
          sudo systemctl stop apparmor || true
          sudo find /etc/apparmor.d -name "slapd*" -exec rm {} \; || true
          sudo apparmor_parser -R /etc/apparmor.d/usr.sbin.slapd 2>/dev/null || true
      - name: 'Set up Python ${{ matrix.python-version }}'
        uses: actions/setup-python@v6
        with:
          python-version: '${{ matrix.python-version }}'
      - uses: actions/checkout@v6
      - run: pip install Flask==$FLASK
        env:
          FLASK: '${{ matrix.FLASK }}'
      - run: pip install -r requirements-dev.txt .
      - run: pip install .
      - run: python -m unittest
